#!/usr/bin/env python3
"""Build the shared web/iOS game using Python's standard library (no npm in Xcode).

python3 scripts/build-game.py                 # web output + local iOS preview bundle
python3 scripts/build-game.py --check         # reject stale tracked web output
python3 scripts/build-game.py --ios-only --ios-output /.../LastPulse.app/GameContent

Source units share a single private game scope, in manifest order. This deliberately
preserves initialization order during extraction; it is not an ES-module migration.
"""
import argparse
import hashlib
import json
from pathlib import Path
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
B64 = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
def vlq(value):
    value = ((-value) << 1 | 1) if value < 0 else value << 1
    result = ''
    while True:
        digit = value & 31
        value >>= 5
        result += B64[digit | (32 if value else 0)]
        if not value:
            return result

def assemble():
    files = json.loads((ROOT / 'src/game/manifest.json').read_text())
    if len(files) != len(set(files)):
        raise ValueError('Duplicate game source in manifest')
    discovered = {str(p.relative_to(ROOT)) for p in (ROOT / 'src/game').rglob('*.js')}
    if set(files) != discovered:
        raise ValueError('Game manifest does not match source files: ' + str(set(files) ^ discovered))
    text = ['// GENERATED by scripts/build-game.py; edit src/game instead.\n', '(function(){\n', '"use strict";\n']
    mappings = ['', '', '']
    sources = []
    prev_source = prev_line = 0
    for idx, name in enumerate(files):
        code = (ROOT / name).read_text().rstrip() + '\n'
        sources.append(code)
        text.append('// ---- ' + name + ' ----\n')
        mappings.append('')
        text.append(code)
        for line_no in range(len(code.splitlines())):
            mappings.append('A' + vlq(idx-prev_source) + vlq(line_no-prev_line) + 'A')
            prev_source, prev_line = idx, line_no
    text += ['})();\n', '//# sourceMappingURL=game.js.map\n']
    smap = dict(version=3, file='game.js', sources=['../../'+p for p in files],
                sourcesContent=sources, names=[], mappings=';'.join(mappings))
    outputs = {
        'index.html': '<!-- GENERATED from src/index.html by scripts/build-game.py -->\n' + (ROOT/'src/index.html').read_text(),
        'assets/game/game.js': ''.join(text),
        'assets/game/game.js.map': json.dumps(smap, separators=(',', ':'))+'\n',
        'assets/game/game.css': (ROOT/'src/styles/game.css').read_text(),
        'assets/game/models3d.js': (ROOT/'src/rendering/models3d.js').read_text(),
    }
    return {p:s.encode() for p,s in outputs.items()}

def put(path, data):
    if path.exists() and path.read_bytes() == data:
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)

def bundle(outputs, destination):
    destination = destination.resolve()
    if destination.name != 'GameContent' or destination in (ROOT, ROOT/'assets', ROOT/'src'):
        raise ValueError('iOS output must be a dedicated GameContent directory')
    expected = set(outputs) | {'manifest.webmanifest'}
    put(destination/'manifest.webmanifest', (ROOT/'manifest.webmanifest').read_bytes())
    for source in (ROOT/'assets').rglob('*'):
        if not source.is_file() or source.name.startswith('.') or 'game' == source.relative_to(ROOT/'assets').parts[0]:
            continue
        rel = str(source.relative_to(ROOT))
        expected.add(rel)
        target = destination/rel
        # Keep resource timestamps stable across repeated Xcode builds.
        if not target.exists() or hashlib.sha256(target.read_bytes()).digest() != hashlib.sha256(source.read_bytes()).digest():
            target.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, target)
    for name, data in outputs.items():
        put(destination/name, data)
    # Only remove files previously managed by this builder, never unknown user files.
    inventory = destination/'.generated-files.json'
    previous = json.loads(inventory.read_text()) if inventory.exists() else []
    for name in set(previous)-expected:
        path = (destination/name).resolve()
        if destination in path.parents and path.is_file():
            path.unlink()
    put(inventory, (json.dumps(sorted(expected),indent=2)+'\n').encode())
    print('iOS content:', destination, '('+str(len(expected))+' files)')

def main():
    parser=argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--ios-only', action='store_true')
    parser.add_argument('--ios-output', type=Path, default=ROOT/'LastPulseIOS/GameContent')
    args=parser.parse_args()
    outputs=assemble()
    if args.check:
        stale=[name for name,data in outputs.items() if not (ROOT/name).exists() or (ROOT/name).read_bytes()!=data]
        if stale:
            sys.exit('Stale generated files; run python3 scripts/build-game.py:\n'+'\n'.join(stale))
        print('Shared-source build is current ('+str(len(outputs))+' web artifacts)')
        return
    if not args.ios_only:
        for name,data in outputs.items():
            put(ROOT/name,data)
        print('Web content built from src/')
    bundle(outputs,args.ios_output)
if __name__=='__main__':
    main()
